services:
  postgres:
    image: postgres:15-alpine
    container_name: ${POSTGRES_CONTAINER}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ${VOLUME_PREFIX}:/var/lib/postgresql/data
    networks:
      - ${NETWORK_NAME}
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  csv-importer:
    build:
      context: ./importer
      dockerfile: Dockerfile
    image: csv-importer:latest
    container_name: ${IMPORTER_CONTAINER}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./data.csv:${CSV_PATH}:ro # read-only para seguridad
    networks:
      - ${NETWORK_NAME}
    environment:
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT}
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      TABLE_NAME: ${TABLE_NAME}
      CSV_PATH: ${CSV_PATH}
      CHUNK_SIZE: ${CHUNK_SIZE}
    restart: "no" # Se ejecuta una vez y se detiene

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ${PGADMIN_CONTAINER}
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - ${VOLUME_PREFIX}_pgadmin:/var/lib/pgadmin
    networks:
      - ${NETWORK_NAME}
    restart: unless-stopped
    depends_on:
      - postgres

volumes:
  db-bienes-servicios:
  db-bienes-servicios_pgadmin:


networks:
  db-bienes-servicios:
    driver: bridge
